// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEFflIGxj4_zVvavnrJXv8hFQIBwOmLDs',
    appId: '1:132256060487:web:fd3b6434e3e335062b8d62',
    messagingSenderId: '132256060487',
    projectId: 'hotel-khan',
    authDomain: 'hotel-khan.firebaseapp.com',
    storageBucket: 'hotel-khan.appspot.com',
    measurementId: 'G-LTZ2HGXKEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdxCtKgSgSfXiLVtBkW-13cmPujxUTIvo',
    appId: '1:132256060487:android:b756719af32a56232b8d62',
    messagingSenderId: '132256060487',
    projectId: 'hotel-khan',
    storageBucket: 'hotel-khan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdVVPLZ-6E4vATMIJOP4jHo1HtiJEA89I',
    appId: '1:132256060487:ios:852ca7b1bbff3fac2b8d62',
    messagingSenderId: '132256060487',
    projectId: 'hotel-khan',
    storageBucket: 'hotel-khan.appspot.com',
    iosBundleId: 'com.example.hotelkhan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdVVPLZ-6E4vATMIJOP4jHo1HtiJEA89I',
    appId: '1:132256060487:ios:dcf0b3d51ceb291c2b8d62',
    messagingSenderId: '132256060487',
    projectId: 'hotel-khan',
    storageBucket: 'hotel-khan.appspot.com',
    iosBundleId: 'com.example.hotelkhan.RunnerTests',
  );
}
